### ISSUE TITLE
Integrate sbt-buildinfo with the command line interface

### ISSUE THREAD

**Issue by frgomes** [frgomes/scala-bindgen#32]
This is what we need in the command line parser:
```scala
object CLI {
  val parser = new scopt.OptionParser[Args](BuildInfo.program) {
    head(BuildInfo.name, BuildInfo.version)

    note(s"""  ${BuildInfo.name} is ${BuildInfo.description}
            |
            |
            |  ${BuildInfo.program} [options...] <files...> [ -- Clang-options...]
            |
            |Options:
            |""".stripMargin)
...
}
```
Notice that ``sbt-buildinfo`` generates the following:
```scala
case object BuildInfo {
  val organization: String = "org.scala-native"
  val name: String = "bindgen"
  val version: String = "0.1-SNAPSHOT"
  val scalaVersion: String = "2.11.11"
  val sbtVersion: String = "0.13.15"

  override val toString: String = {
    "organization: %s, name: %s, version: %s, scalaVersion: %s, sbtVersion: %s" format (
      organization, name, version, scalaVersion, sbtVersion
    )
  }
}
```
However, this code crashes. I had to substitute manually by:
```scala
case object BuildInfo {
  val organization: String = "org.scala-native"
  val name: String = "bindgen"
  val version: String = "0.1-SNAPSHOT"
  val scalaVersion: String = "2.11.11"
  val sbtVersion: String = "0.13.15"

  // THIS IS A HACK
  override val toString: String = {
    "organization: ${organization}, name: ${name}, version: ${version}, scalaVersion: ${scalaVersion}, sbtVersion: ${sbtVersion}"
  }
}
```

**Comment by frgomes** [comment]
```
> bindgen/run --help
[info] Updating {file:/home/rgomes/workspace/scala-bindgen/}bindgen...
[info] Resolving org.scala-native#javalib_native0.3_2.11;0.3.1 ...
[info] Compiling /home/rgomes/workspace/scala-bindgen/bindgen/src/main/resources/clang.c to /home/rgomes/workspace/scala-bindgen/bindgen/target/scala-2.11/clang.o
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 3 Scala sources to /home/rgomes/workspace/scala-bindgen/bindgen/target/scala-2.11/classes...
[info] Linking (3092 ms)
[info] Discovered 1437 classes and 10500 methods
[info] Optimizing (6369 ms)
[info] Generating intermediate code (1614 ms)
[info] Produced 53 files
[info] Compiling to native code (3608 ms)
[info] Linking native code (397 ms)
scala.NotImplementedError: an implementation is missing
        at java.lang.Throwable.init(Unknown Source)
        at java.lang.Error.init(Unknown Source)
        at java.lang.Error.init(Unknown Source)
        at scala.NotImplementedError.init(Unknown Source)
        at scala.NotImplementedError.init(Unknown Source)
        at scala.Predef$.???(Unknown Source)
        at java.util.Formatter.format(Unknown Source)
        at java.lang.String$.format(Unknown Source)
        at java.lang.String$.format(Unknown Source)
        at scala.collection.immutable.StringLike$class$.format(Unknown Source)
        at scala.collection.immutable.StringOps.format(Unknown Source)
        at bindgen.buildinfo.BuildInfo$.init(Unknown Source)
        at bindgen.buildinfo.BuildInfo$.load(Unknown Source)
        at bindgen.CLI$.init(Unknown Source)
        at bindgen.CLI$.load(Unknown Source)
        at bindgen.Main$.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
        at <none>.(Unknown Source)
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last bindgen/compile:run for the full output.
[error] (bindgen/compile:run) Nonzero exit code: 1
[error] Total time: 29 s, completed 10-Jul-2017 05:13:22
```
